// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = ContentcardSlice;

/**
 * Content for Pagina documents
 */
interface PageDocumentData {
  /**
   * Titel field in *Pagina*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Pagina naam
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Prioriteit field in *Pagina*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Plek in het menu (links > rechts)
   * - **API ID Path**: page.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * Hoofdpagina field in *Pagina*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Pagina*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Pagina*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Pagina*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Pagina*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Pagina document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Social → Social Media Bron*
 */
export interface SocialDocumentDataSocialItemItem {
  /**
   * Icon SVG field in *Social → Social Media Bron*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Plaats de <svg></svg> inhoud voor een icon
   * - **API ID Path**: social.social_item[].icon
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  icon: prismic.RichTextField;

  /**
   * Link field in *Social → Social Media Bron*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Social media website url
   * - **API ID Path**: social.social_item[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Social documents
 */
interface SocialDocumentData {
  /**
   * Social Media Bron field in *Social*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social.social_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_item: prismic.GroupField<Simplify<SocialDocumentDataSocialItemItem>>;
}

/**
 * Social document from Prismic
 *
 * - **API ID**: `social`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SocialDocumentData>,
    "social",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SocialDocument;

/**
 * Primary content in *ContentCard → InfoCard → Primary*
 */
export interface ContentcardSliceDefaultPrimary {
  /**
   * Icon field in *ContentCard → InfoCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Icon
   * - **API ID Path**: contentcard.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon: prismic.KeyTextField;

  /**
   * Titel field in *ContentCard → InfoCard → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Titel
   * - **API ID Path**: contentcard.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Inhoud field in *ContentCard → InfoCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Inhoud
   * - **API ID Path**: contentcard.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Hyperlink field in *ContentCard → InfoCard → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Hyperlink
   * - **API ID Path**: contentcard.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * InfoCard variation for ContentCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentcardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentcardSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ContentCard → NewsCard → Primary*
 */
export interface ContentcardSliceNewsCardPrimary {
  /**
   * Foto field in *ContentCard → NewsCard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contentcard.newsCard.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Datum field in *ContentCard → NewsCard → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Datum
   * - **API ID Path**: contentcard.newsCard.primary.date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Titel field in *ContentCard → NewsCard → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Titel
   * - **API ID Path**: contentcard.newsCard.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Inhoud field in *ContentCard → NewsCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Inhoud
   * - **API ID Path**: contentcard.newsCard.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Hyperlink field in *ContentCard → NewsCard → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Hyperlink
   * - **API ID Path**: contentcard.newsCard.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * NewsCard variation for ContentCard Slice
 *
 * - **API ID**: `newsCard`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentcardSliceNewsCard = prismic.SharedSliceVariation<
  "newsCard",
  Simplify<ContentcardSliceNewsCardPrimary>,
  never
>;

/**
 * Slice variation for *ContentCard*
 */
type ContentcardSliceVariation =
  | ContentcardSliceDefault
  | ContentcardSliceNewsCard;

/**
 * ContentCard Shared Slice
 *
 * - **API ID**: `contentcard`
 * - **Description**: Contentcard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentcardSlice = prismic.SharedSlice<
  "contentcard",
  ContentcardSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SocialDocument,
      SocialDocumentData,
      SocialDocumentDataSocialItemItem,
      AllDocumentTypes,
      ContentcardSlice,
      ContentcardSliceDefaultPrimary,
      ContentcardSliceNewsCardPrimary,
      ContentcardSliceVariation,
      ContentcardSliceDefault,
      ContentcardSliceNewsCard,
    };
  }
}
