// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  archive: dynamic(() => import("./Archive")),
  content_cards: dynamic(() => import("./ContentCards")),
  contentcard: dynamic(() => import("./InfoCards")),
  latest_news: dynamic(() => import("./LatestNews")),
  section: dynamic(() => import("./Section")),
};
